### ISSUE TITLE
Latest rename introduced bugs

### ISSUE THREAD

**Issue by Tobias-Fischer** [uzh-rpg/rpg_vid2e#23]
https://github.com/uzh-rpg/rpg_vid2e/commit/52bb812b609084d1f8265f6877801426fd2c1cff leads to:

```
(vid2e) tobias@QUTLAB:~/robot/rpg_vid2e/esim_torch$ python test.py
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    refractory_period=0)
TypeError: __init__() got an unexpected keyword argument 'refractory_period'
(vid2e) tobias@QUTLAB:~/robot/rpg_vid2e/esim_torch$ python test_single_pixel.py 
Traceback (most recent call last):
  File "test_single_pixel.py", line 17, in <module>
    refractory_period=refractory_period)
TypeError: __init__() got an unexpected keyword argument 'refractory_period'
(vid2e) tobias@QUTLAB:~/robot/rpg_vid2e/esim_torch$ 
```

**Comment by danielgehrig18** [comment]
Nice catch. Just fixed it.
