### ISSUE TITLE
Building esim_torch does not work

### ISSUE THREAD

**Issue by c6s0** [uzh-rpg/rpg_vid2e#27]
Hey, 

everything worked so far on win10, but the ```pip install esim_torch``` step does not work. 

Also, it is not clear to me what is meant by ``` conda config --add pytorch```, since the command leads to this output:
 ```conda-script.py config: error: argument --prepend/--add: expected 2 arguments ```

Thats the error i get after pip install esim_torch/:

 ```(vid2e) C:\Users\hello\Documents\rpg_vid2e>pip install esim_torch/
Processing c:\users\hello\documents\rpg_vid2e\esim_torch
Building wheels for collected packages: esim-cuda
  Building wheel for esim-cuda (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\hello\anaconda3\envs\vid2e\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"
'C:\\Users\\hello\\AppData\\Local\\Temp\\pip-req-build-10_fou08\\setup.py'"'"'; __file__='"'"'C:\\Users\\hello\\AppData\
\Local\\Temp\\pip-req-build-10_fou08\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().re
place('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\he
llo\AppData\Local\Temp\pip-wheel-jg9alm38'
       cwd: C:\Users\hello\AppData\Local\Temp\pip-req-build-10_fou08\
  Complete output (92 lines):
  running bdist_wheel
  running build
  running build_ext
  C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\utils\cpp_extension.py:304: UserWarning: Error checking co
mpiler version for cl: [WinError 2] Das System kann die angegebene Datei nicht finden
    warnings.warn(f'Error checking compiler version for {compiler}: {error}')
  building 'esim_cuda' extension
  creating C:\Users\hello\AppData\Local\Temp\pip-req-build-10_fou08\build
  creating C:\Users\hello\AppData\Local\Temp\pip-req-build-10_fou08\build\temp.win-amd64-3.7
  creating C:\Users\hello\AppData\Local\Temp\pip-req-build-10_fou08\build\temp.win-amd64-3.7\Release
  Emitting ninja build file C:\Users\hello\AppData\Local\Temp\pip-req-build-10_fou08\build\temp.win-amd64-3.7\Release\bu
ild.ninja...
  Compiling objects...
  Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
  [1/1] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin\nvcc  --use-local-env -Xcompiler /MD -Xcompiler /wd
4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -
Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_d
ll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflic
t_dllexport_assumed -IC:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\include -IC:\Users\hello\anaconda3\env
s\vid2e\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\t
orch\include\TH -IC:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU
 Computing Toolkit\CUDA\v11.4\include" -IC:\Users\hello\anaconda3\envs\vid2e\include -IC:\Users\hello\anaconda3\envs\vid
2e\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-
IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x
86)\Windows Kits\NETFXSDK\4.7.2\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\P
rogram Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.1
9041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\
10\include\10.0.19041.0\cppwinrt" -c C:\Users\hello\AppData\Local\Temp\pip-req-build-10_fou08\esim_cuda_kernel.cu -o C:\
Users\hello\AppData\Local\Temp\pip-req-build-10_fou08\build\temp.win-amd64-3.7\Release\esim_cuda_kernel.obj -D__CUDA_NO_
HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-
relaxed-constexpr -arch=sm_60 -O3 -use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=esim_cuda -D_GLI
BCXX_USE_CXX11_ABI=0
  FAILED: C:/Users/hello/AppData/Local/Temp/pip-req-build-10_fou08/build/temp.win-amd64-3.7/Release/esim_cuda_kernel.obj
  C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin\nvcc  --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -
Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompi
ler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_int
erface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dlle
xport_assumed -IC:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\include -IC:\Users\hello\anaconda3\envs\vid2
e\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\i
nclude\TH -IC:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Compu
ting Toolkit\CUDA\v11.4\include" -IC:\Users\hello\anaconda3\envs\vid2e\include -IC:\Users\hello\anaconda3\envs\vid2e\inc
lude "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Pr
ogram Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Wi
ndows Kits\NETFXSDK\4.7.2\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program
 Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0
\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\inc
lude\10.0.19041.0\cppwinrt" -c C:\Users\hello\AppData\Local\Temp\pip-req-build-10_fou08\esim_cuda_kernel.cu -o C:\Users\
hello\AppData\Local\Temp\pip-req-build-10_fou08\build\temp.win-amd64-3.7\Release\esim_cuda_kernel.obj -D__CUDA_NO_HALF_O
PERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxe
d-constexpr -arch=sm_60 -O3 -use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=esim_cuda -D_GLIBCXX_U
SE_CXX11_ABI=0
  C:/Users/hello/anaconda3/envs/vid2e/lib/site-packages/torch/include\c10/macros/Macros.h(189): warning C4067: Unerwarte
te Token nach PrÃ¤prozessordirektive - Zeilenvorschub erwartet.
  C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\include\pybind11\detail/common.h(108): warning C4005: "HAV
E_SNPRINTF": Makro-Neudefinition
  C:\Users\hello\anaconda3\envs\vid2e\include\pyerrors.h(490): note: Siehe vorherige Definition von "HAVE_SNPRINTF"
  C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\include\pybind11\cast.h(1429): error: too few arguments fo
r template template parameter "Tuple"
            detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair,
Ts=<T1, T2>]"
  (1507): here

  C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\include\pybind11\cast.h(1503): error: too few arguments fo
r template template parameter "Tuple"
            detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair,
Ts=<T1, T2>]"
  (1507): here

  c:\users\hello\appdata\local\temp\pip-req-build-10_fou08\esim_cuda_kernel.cu(39): warning: variable "i0" was declared
but never referenced
            detected during instantiation of "void count_events_cuda_forward_kernel(const scalar_t *, const scalar_t *,
scalar_t *, int64_t *, int, int, int, float, float) [with scalar_t=float]"
  (152): here

  2 errors detected in the compilation of "c:/users/hello/appdata/local/temp/pip-req-build-10_fou08/esim_cuda_kernel.cu"
.
  esim_cuda_kernel.cu
  ninja: build stopped: subcommand failed.
  Traceback (most recent call last):
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\utils\cpp_extension.py", line 1673, in _run_ninja_
build
      env=env)
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\subprocess.py", line 512, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\hello\AppData\Local\Temp\pip-req-build-10_fou08\setup.py", line 17, in <module>
      'build_ext': BuildExtension
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
      _build_ext.run(self)
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\utils\cpp_extension.py", line 708, in build_extens
ions
      build_ext.build_extensions(self)
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_ext
ension
      _build_ext.build_extension(self, ext)
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\command\build_ext.py", line 534, in build_extension
      depends=ext.depends)
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\utils\cpp_extension.py", line 690, in win_wrap_nin
ja_compile
      with_cuda=with_cuda)
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\utils\cpp_extension.py", line 1359, in _write_ninj
a_file_and_compile_objects
      error_prefix='Error compiling objects for extension')
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\utils\cpp_extension.py", line 1683, in _run_ninja_
build
      raise RuntimeError(message) from e
  RuntimeError: Error compiling objects for extension
  Error in atexit._run_exitfuncs:
  Traceback (most recent call last):
    File "C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
      return stream.closed
  ValueError: underlying buffer has been detached
  ----------------------------------------
  ERROR: Failed building wheel for esim-cuda
  Running setup.py clean for esim-cuda
Failed to build esim-cuda
Installing collected packages: esim-cuda
    Running setup.py install for esim-cuda ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\hello\anaconda3\envs\vid2e\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"
'"'C:\\Users\\hello\\AppData\\Local\\Temp\\pip-req-build-10_fou08\\setup.py'"'"'; __file__='"'"'C:\\Users\\hello\\AppDat
a\\Local\\Temp\\pip-req-build-10_fou08\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().
replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\User
s\hello\AppData\Local\Temp\pip-record-zogla9qx\install-record.txt' --single-version-externally-managed --compile --insta
ll-headers 'C:\Users\hello\anaconda3\envs\vid2e\Include\esim-cuda'
         cwd: C:\Users\hello\AppData\Local\Temp\pip-req-build-10_fou08\
    Complete output (94 lines):
    running install
    running build
    running build_ext
    C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\utils\cpp_extension.py:304: UserWarning: Error checking
compiler version for cl: [WinError 2] Das System kann die angegebene Datei nicht finden
      warnings.warn(f'Error checking compiler version for {compiler}: {error}')
    building 'esim_cuda' extension
    creating C:\Users\hello\AppData\Local\Temp\pip-req-build-10_fou08\build
    creating C:\Users\hello\AppData\Local\Temp\pip-req-build-10_fou08\build\temp.win-amd64-3.7
    creating C:\Users\hello\AppData\Local\Temp\pip-req-build-10_fou08\build\temp.win-amd64-3.7\Release
    Emitting ninja build file C:\Users\hello\AppData\Local\Temp\pip-req-build-10_fou08\build\temp.win-amd64-3.7\Release\
build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    [1/1] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin\nvcc  --use-local-env -Xcompiler /MD -Xcompiler /
wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190
 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without
_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_confl
ict_dllexport_assumed -IC:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\include -IC:\Users\hello\anaconda3\e
nvs\vid2e\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\hello\anaconda3\envs\vid2e\lib\site-packages
\torch\include\TH -IC:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA G
PU Computing Toolkit\CUDA\v11.4\include" -IC:\Users\hello\anaconda3\envs\vid2e\include -IC:\Users\hello\anaconda3\envs\v
id2e\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include"
"-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files
(x86)\Windows Kits\NETFXSDK\4.7.2\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:
\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0
.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kit
s\10\include\10.0.19041.0\cppwinrt" -c C:\Users\hello\AppData\Local\Temp\pip-req-build-10_fou08\esim_cuda_kernel.cu -o C
:\Users\hello\AppData\Local\Temp\pip-req-build-10_fou08\build\temp.win-amd64-3.7\Release\esim_cuda_kernel.obj -D__CUDA_N
O_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --exp
t-relaxed-constexpr -arch=sm_60 -O3 -use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=esim_cuda -D_G
LIBCXX_USE_CXX11_ABI=0
    FAILED: C:/Users/hello/AppData/Local/Temp/pip-req-build-10_fou08/build/temp.win-amd64-3.7/Release/esim_cuda_kernel.o
bj
    C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin\nvcc  --use-local-env -Xcompiler /MD -Xcompiler /wd4819
 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcom
piler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_i
nterface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dl
lexport_assumed -IC:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\include -IC:\Users\hello\anaconda3\envs\vi
d2e\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch
\include\TH -IC:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Com
puting Toolkit\CUDA\v11.4\include" -IC:\Users\hello\anaconda3\envs\vid2e\include -IC:\Users\hello\anaconda3\envs\vid2e\i
nclude "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\
Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\
Windows Kits\NETFXSDK\4.7.2\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Progr
am Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041
.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\i
nclude\10.0.19041.0\cppwinrt" -c C:\Users\hello\AppData\Local\Temp\pip-req-build-10_fou08\esim_cuda_kernel.cu -o C:\User
s\hello\AppData\Local\Temp\pip-req-build-10_fou08\build\temp.win-amd64-3.7\Release\esim_cuda_kernel.obj -D__CUDA_NO_HALF
_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-rela
xed-constexpr -arch=sm_60 -O3 -use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=esim_cuda -D_GLIBCXX
_USE_CXX11_ABI=0
    C:/Users/hello/anaconda3/envs/vid2e/lib/site-packages/torch/include\c10/macros/Macros.h(189): warning C4067: Unerwar
tete Token nach PrÃ¤prozessordirektive - Zeilenvorschub erwartet.
    C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\include\pybind11\detail/common.h(108): warning C4005: "H
AVE_SNPRINTF": Makro-Neudefinition
    C:\Users\hello\anaconda3\envs\vid2e\include\pyerrors.h(490): note: Siehe vorherige Definition von "HAVE_SNPRINTF"
    C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\include\pybind11\cast.h(1429): error: too few arguments
for template template parameter "Tuple"
              detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair
, Ts=<T1, T2>]"
    (1507): here

    C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\include\pybind11\cast.h(1503): error: too few arguments
for template template parameter "Tuple"
              detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair
, Ts=<T1, T2>]"
    (1507): here

    c:\users\hello\appdata\local\temp\pip-req-build-10_fou08\esim_cuda_kernel.cu(39): warning: variable "i0" was declare
d but never referenced
              detected during instantiation of "void count_events_cuda_forward_kernel(const scalar_t *, const scalar_t *
, scalar_t *, int64_t *, int, int, int, float, float) [with scalar_t=float]"
    (152): here

    2 errors detected in the compilation of "c:/users/hello/appdata/local/temp/pip-req-build-10_fou08/esim_cuda_kernel.c
u".
    esim_cuda_kernel.cu
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\utils\cpp_extension.py", line 1673, in _run_ninj
a_build
        env=env)
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\hello\AppData\Local\Temp\pip-req-build-10_fou08\setup.py", line 17, in <module>
        'build_ext': BuildExtension
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
        _build_ext.run(self)
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\utils\cpp_extension.py", line 708, in build_exte
nsions
        build_ext.build_extensions(self)
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\command\build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\command\build_ext.py", line 474, in _build_extensions_seri
al
        self.build_extension(ext)
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_e
xtension
        _build_ext.build_extension(self, ext)
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\distutils\command\build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\utils\cpp_extension.py", line 690, in win_wrap_n
inja_compile
        with_cuda=with_cuda)
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\utils\cpp_extension.py", line 1359, in _write_ni
nja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\utils\cpp_extension.py", line 1683, in _run_ninj
a_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
        return stream.closed
    ValueError: underlying buffer has been detached
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\hello\anaconda3\envs\vid2e\python.exe' -u -c 'import sys, setup
tools, tokenize; sys.argv[0] = '"'"'C:\\Users\\hello\\AppData\\Local\\Temp\\pip-req-build-10_fou08\\setup.py'"'"'; __fil
e__='"'"'C:\\Users\\hello\\AppData\\Local\\Temp\\pip-req-build-10_fou08\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"
', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'
"'"'))' install --record 'C:\Users\hello\AppData\Local\Temp\pip-record-zogla9qx\install-record.txt' --single-version-ext
ernally-managed --compile --install-headers 'C:\Users\hello\anaconda3\envs\vid2e\Include\esim-cuda' Check the logs for f
ull command output.  ```

**Comment by danielgehrig18** [comment]
Hi, yes I fixed the command. It should be `conda config --add channel pytorch`. 

It seems that the error comes from these lines: 

>  C:\Users\hello\anaconda3\envs\vid2e\include\pyerrors.h(490): note: Siehe vorherige Definition von "HAVE_SNPRINTF"
 C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\include\pybind11\cast.h(1429): error: too few arguments fo
r template template parameter "Tuple"
           detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair,
Ts=<T1, T2>]"
 (1507): here

> C:\Users\hello\anaconda3\envs\vid2e\lib\site-packages\torch\include\pybind11\cast.h(1503): error: too few arguments fo
r template template parameter "Tuple"
           detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair,
Ts=<T1, T2>]"
 (1507): here

Which might indicate a problem with the cpp or pybind version. Did you check online if there is a solution to this?

**Comment by c6s0** [comment]
thank you for the answer!
i tried it with pytorch 1.4 but still get the error messages, but i was able to compile esim_torch on ubuntu in a VM. 
if someone still manages to compile esim_torch on windows i would be very interested in how it works!
