### ISSUE TITLE
Building python bindings for ESIM

### ISSUE THREAD

**Issue by jprodriguezg** [uzh-rpg/rpg_vid2e#3]
Hi!

I am having an error by trying to build the python bindings for ESIM.
When I run  `pip install .` in the esim_py folder using the `(vid2e)` environment, I got the following error:

```
ERROR: Command errored out with exit status 1:
   command: /home/juan/Software/Anacoda2/envs/vid2e/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-az36ldis/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-az36ldis/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-xflbexrp
       cwd: /tmp/pip-req-build-az36ldis/
  Complete output (155 lines):
  running bdist_wheel
  running build
  running build_ext
  -- The C compiler identification is GNU 5.5.0
  -- The CXX compiler identification is GNU 5.5.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /home/juan/Software/Anacoda2/envs/vid2e/bin/python (found version "3.7.7")
  -- Found PythonLibs: /home/juan/Software/Anacoda2/envs/vid2e/lib/libpython3.7m.so
  -- Performing Test HAS_CPP14_FLAG
  -- Performing Test HAS_CPP14_FLAG - Success
  -- Found OpenCV: /opt/ros/kinetic (found version "3.3.1")
  -- Found Boost 1.70.0 at /home/juan/Software/Anacoda2/envs/vid2e/lib/cmake/Boost-1.70.0
  --   Requested configuration: QUIET REQUIRED COMPONENTS system;filesystem
  -- Found boost_headers 1.70.0 at /home/juan/Software/Anacoda2/envs/vid2e/lib/cmake/boost_headers-1.70.0
  -- Found boost_system 1.70.0 at /home/juan/Software/Anacoda2/envs/vid2e/lib/cmake/boost_system-1.70.0
  --   libboost_system.a
  -- Adding boost_system dependencies: headers
  -- Found boost_filesystem 1.70.0 at /home/juan/Software/Anacoda2/envs/vid2e/lib/cmake/boost_filesystem-1.70.0
  --   libboost_filesystem.a
  -- Adding boost_filesystem dependencies: headers
  -- Found Boost: /home/juan/Software/Anacoda2/envs/vid2e/lib/cmake/Boost-1.70.0/BoostConfig.cmake (found version "1.70.0") found components:  system filesystem
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- LTO enabled
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-req-build-az36ldis/build/temp.linux-x86_64-3.7
  Scanning dependencies of target libesim
  [ 25%] Building CXX object CMakeFiles/libesim.dir/src/esim.cpp.o
  In file included from /tmp/pip-req-build-az36ldis/src/esim.cpp:1:0:
  /tmp/pip-req-build-az36ldis/include/esim.h: In member function ‘void EventSimulator::read_directory_from_path(const string&, std::vector<std::__cxx11::basic_string<char> >&)’:
  /tmp/pip-req-build-az36ldis/include/esim.h:87:12: error: ‘path_leaf_string’ does not name a type
         auto path_leaf_string = [](const boost::filesystem::directory_entry& entry) -> std::string {return entry.path().string();};
              ^
  In file included from /tmp/pip-req-build-az36ldis/src/esim.cpp:1:0:
  /tmp/pip-req-build-az36ldis/include/esim.h:89:57: error: ‘path_leaf_string’ was not declared in this scope
         std::transform(start, end, std::back_inserter(v), path_leaf_string);
                                                           ^
  /tmp/pip-req-build-az36ldis/src/esim.cpp: In member function ‘Eigen::MatrixXd EventSimulator::generateFromVideo(std::__cxx11::string, std::__cxx11::string)’:
  /tmp/pip-req-build-az36ldis/src/esim.cpp:25:55: error: no matching function for call to ‘std::basic_ifstream<char>::basic_ifstream(std::__cxx11::string&)’
       std::ifstream timestamps_file(timestamps_file_path);
                                                         ^
  In file included from /home/juan/Software/Anacoda2/envs/vid2e/include/boost/filesystem/fstream.hpp:23:0,
                   from /home/juan/Software/Anacoda2/envs/vid2e/include/boost/filesystem/string_file.hpp:14,
                   from /home/juan/Software/Anacoda2/envs/vid2e/include/boost/filesystem.hpp:19,
                   from /tmp/pip-req-build-az36ldis/include/esim.h:5,
                   from /tmp/pip-req-build-az36ldis/src/esim.cpp:1:
  /usr/include/c++/5/fstream:495:7: note: candidate: std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
         basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in)
         ^
  /usr/include/c++/5/fstream:495:7: note:   no known conversion for argument 1 from ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to ‘const char*’
  /usr/include/c++/5/fstream:481:7: note: candidate: std::basic_ifstream<_CharT, _Traits>::basic_ifstream() [with _CharT = char; _Traits = std::char_traits<char>]
         basic_ifstream() : __istream_type(), _M_filebuf()
         ^
  /usr/include/c++/5/fstream:481:7: note:   candidate expects 0 arguments, 1 provided
  /usr/include/c++/5/fstream:455:11: note: candidate: std::basic_ifstream<char>::basic_ifstream(const std::basic_ifstream<char>&)
       class basic_ifstream : public basic_istream<_CharT, _Traits>
             ^
  /usr/include/c++/5/fstream:455:11: note:   no known conversion for argument 1 from ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to ‘const std::basic_ifstream<char>&’
  /tmp/pip-req-build-az36ldis/src/esim.cpp:53:16: error: ‘stod’ is not a member of ‘std’
           time = std::stod(time_str);
                  ^
  /tmp/pip-req-build-az36ldis/src/esim.cpp: In member function ‘Eigen::MatrixXd EventSimulator::generateFromStampedImageSequence(std::vector<std::__cxx11::basic_string<char> >, std::vector<double, std::allocator<double> >)’:
  /tmp/pip-req-build-az36ldis/src/esim.cpp:68:107: error: ‘to_string’ is not a member of ‘std’
           throw std::runtime_error("Number of image paths and number of timestamps should be equal. Got " + std::to_string(image_paths.size()) + " and " + std::to_string(timestamps.size()));
                                                                                                             ^
  /tmp/pip-req-build-az36ldis/src/esim.cpp:68:154: error: ‘to_string’ is not a member of ‘std’
           throw std::runtime_error("Number of image paths and number of timestamps should be equal. Got " + std::to_string(image_paths.size()) + " and " + std::to_string(timestamps.size()));
                                                                                                                                                            ^
  /tmp/pip-req-build-az36ldis/src/esim.cpp: In member function ‘Eigen::MatrixXd EventSimulator::generateFromFolder(std::__cxx11::string, std::__cxx11::string)’:
  /tmp/pip-req-build-az36ldis/src/esim.cpp:108:55: error: no matching function for call to ‘std::basic_ifstream<char>::basic_ifstream(std::__cxx11::string&)’
       std::ifstream timestamps_file(timestamps_file_path);
                                                         ^
  In file included from /home/juan/Software/Anacoda2/envs/vid2e/include/boost/filesystem/fstream.hpp:23:0,
                   from /home/juan/Software/Anacoda2/envs/vid2e/include/boost/filesystem/string_file.hpp:14,
                   from /home/juan/Software/Anacoda2/envs/vid2e/include/boost/filesystem.hpp:19,
                   from /tmp/pip-req-build-az36ldis/include/esim.h:5,
                   from /tmp/pip-req-build-az36ldis/src/esim.cpp:1:
  /usr/include/c++/5/fstream:495:7: note: candidate: std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
         basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in)
         ^
  /usr/include/c++/5/fstream:495:7: note:   no known conversion for argument 1 from ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to ‘const char*’
  /usr/include/c++/5/fstream:481:7: note: candidate: std::basic_ifstream<_CharT, _Traits>::basic_ifstream() [with _CharT = char; _Traits = std::char_traits<char>]
         basic_ifstream() : __istream_type(), _M_filebuf()
         ^
  /usr/include/c++/5/fstream:481:7: note:   candidate expects 0 arguments, 1 provided
  /usr/include/c++/5/fstream:455:11: note: candidate: std::basic_ifstream<char>::basic_ifstream(const std::basic_ifstream<char>&)
       class basic_ifstream : public basic_istream<_CharT, _Traits>
             ^
  /usr/include/c++/5/fstream:455:11: note:   no known conversion for argument 1 from ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to ‘const std::basic_ifstream<char>&’
  /tmp/pip-req-build-az36ldis/src/esim.cpp:120:36: warning: range-based ‘for’ loops only available with -std=c++11 or -std=gnu++11
       for (const std::string& file : image_files)
                                      ^
  /tmp/pip-req-build-az36ldis/src/esim.cpp:135:16: error: ‘stod’ is not a member of ‘std’
           time = std::stod(time_str);
                  ^
  /tmp/pip-req-build-az36ldis/src/esim.cpp: In member function ‘void EventSimulator::imageCallback(const cv::Mat&, double, std::vector<Event>&)’:
  /tmp/pip-req-build-az36ldis/src/esim.cpp:172:12: error: ‘constexpr’ does not name a type
       static constexpr double kTolerance = 1e-6;
              ^
  /tmp/pip-req-build-az36ldis/src/esim.cpp:172:12: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
  /tmp/pip-req-build-az36ldis/src/esim.cpp:183:41: error: ‘kTolerance’ was not declared in this scope
               if (std::fabs (it - itdt) > kTolerance)
                                           ^
  /tmp/pip-req-build-az36ldis/src/esim.cpp:207:40: error: ‘class std::vector<Event>’ has no member named ‘emplace_back’
                               new_events.emplace_back(x, y,t,pol);
                                          ^
  CMakeFiles/libesim.dir/build.make:62: recipe for target 'CMakeFiles/libesim.dir/src/esim.cpp.o' failed
  make[2]: *** [CMakeFiles/libesim.dir/src/esim.cpp.o] Error 1
  CMakeFiles/Makefile2:77: recipe for target 'CMakeFiles/libesim.dir/all' failed
  make[1]: *** [CMakeFiles/libesim.dir/all] Error 2
  Makefile:83: recipe for target 'all' failed
  make: *** [all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-az36ldis/setup.py", line 62, in <module>
      zip_safe=False,
    File "/home/juan/Software/Anacoda2/envs/vid2e/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/home/juan/Software/Anacoda2/envs/vid2e/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/juan/Software/Anacoda2/envs/vid2e/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/juan/Software/Anacoda2/envs/vid2e/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/juan/Software/Anacoda2/envs/vid2e/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/home/juan/Software/Anacoda2/envs/vid2e/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/juan/Software/Anacoda2/envs/vid2e/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/juan/Software/Anacoda2/envs/vid2e/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/juan/Software/Anacoda2/envs/vid2e/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/juan/Software/Anacoda2/envs/vid2e/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-az36ldis/setup.py", line 31, in run
      self.build_extension(ext)
    File "/tmp/pip-req-build-az36ldis/setup.py", line 50, in build_extension
      subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
    File "/home/juan/Software/Anacoda2/envs/vid2e/lib/python3.7/subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for esim-py
```

I followed the installation guide. Perhaps there is a missing dependency for esim_py.  Could you please help to solve this issue?

Best,

**Comment by magehrig** [comment]
It seems that your compiler is not using C++11 for compiling. Could you `git checkout fix/issue3` and try the installation from scratch again?

**Comment by jprodriguezg** [comment]
You are right, my compiler was not using C++ 11. I did  `git checkout fix/issue3` but I still had the same issue. I modified the `esim_py/CMakeLists.txt` by adding `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -O3 -march=native" )` and now it compiles correctly.  

Thanks for the hint!!
