### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by DachunKai** [uzh-rpg/rpg_vid2e#31]
When I run the last command, I meet the error:
```python
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1573049306803/work/aten/src/THC/THCGeneral.cpp line=371 error=98 : invalid device function
Traceback (most recent call last):
  File "esim_torch/generate_events.py", line 72, in <module>
    process_dir(output_folder, path, args)
  File "esim_torch/generate_events.py", line 40, in process_dir
    sub_events = esim.forward(log_image, timestamp_ns)
  File "/code/rpg_vid2e/esim_torch/esim_torch.py", line 49, in forward
    events = self.initialized_forward(images, timestamps)
  File "/code/rpg_vid2e/esim_torch/esim_torch.py", line 73, in initialized_forward
    cumsum = event_counts.view(-1).cumsum(dim=0)
RuntimeError: cuda runtime error (98) : invalid device function at /opt/conda/conda-bld/pytorch_1573049306803/work/aten/src/THC/THCGeneral.cpp:371
  0%|                                                      | 0/56 [00:00<?, ?it/s]
Segmentation fault (core dumped)
```
What's the reason?

**Comment by magehrig** [comment]
Can you report on your cuda driver and cuda toolkit version?

You have to ensure that the cuda toolkit is supported by the cuda driver version on your system.

**Comment by DachunKai** [comment]
Hi, I tested the cuda driver and cudatoolkit version.
`nvcc -V` report that cudatoolkit version is 10.0 and `nvidia-smi` report that cuda driver version is 10.1. Is this problem?
I have searched that if cuda driver version(10.1) is greater than cudatoolkit version(10.0). Most should not go wrong.
