### ISSUE TITLE
Error when running esim_torch/generate_events.py - cuda runtime error (209) : no kernel image is available

### ISSUE THREAD

**Issue by ashantanu** [uzh-rpg/rpg_vid2e#32]
Thank you for this incredible work. I followed all the setup instructions to set up the environment on google colab. I was able to build esim_torch and run upsampling. I can also run upsampling with device=cuda:0. But when I try to run esim_torch/generate_events.py, I get the following error:

```
Generating events with cn=0.2, cp=0.2 and rp=0
Processing folder example/upsampled/dirname_does_not_matter... Generating events in example/events/dirname_does_not_matter
  0%|                                                                                                                          | 0/56 [00:00<?, ?it/s]THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1573049306803/work/aten/src/THC/THCGeneral.cpp line=371 error=209 : no kernel image is available for execution on the device
Traceback (most recent call last):
  File "esim_torch/generate_events.py", line 72, in <module>
    process_dir(output_folder, path, args)
  File "esim_torch/generate_events.py", line 40, in process_dir
    sub_events = esim.forward(log_image, timestamp_ns)
  File "/content/drive/MyDrive/NN_682/rpg_vid2e/esim_torch/esim_torch.py", line 49, in forward
    events = self.initialized_forward(images, timestamps)
  File "/content/drive/MyDrive/NN_682/rpg_vid2e/esim_torch/esim_torch.py", line 73, in initialized_forward
    cumsum = event_counts.view(-1).cumsum(dim=0)
RuntimeError: cuda runtime error (209) : no kernel image is available for execution on the device at /opt/conda/conda-bld/pytorch_1573049306803/work/aten/src/THC/THCGeneral.cpp:371
  0%|                                                                                                                          | 0/56 [00:00<?, ?it/s]
```
I understand this means that the GPU is not supported for the pytorch version being used. Following are the details of GPU on colab:
```
  
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.63.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   72C    P8    34W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

I used miniconda on colab to setup the python environment.
```
conda 4.10.3
Python 3.7.11
```

Pytorch version
```
rpg_vid2e# conda list pytorch
# packages in environment at /usr/local/envs/vid2e:
#
# Name                    Version                   Build  Channel
_pytorch_select           0.1                       cpu_0  
pytorch                   1.3.1           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
```

I have to run on colab because I don't have my own GPU. Some threads mention building pytorch from source but I am not familiar the steps to setup an older pytorch version. I was hoping for an easier resolution.
Please let me know what can be done to resolve this. Let me know what other details/logs are needed for more information.

Also, is there a way to run this without GPU? Just for making sure this runs and everything else is okay.

Thanks!

**Comment by ashantanu** [comment]
I was able to successfully run the following script on my colab in vid2e conda environment. This makes me believe there is some issue when installing esim_torch. 

```
import torch
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(1, 10),
    nn.ReLU(),
    nn.Linear(10, 1)
)

optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
x = torch.randn(5, 1)
y = torch.randn(5, 1)
model = model.cuda()
x = x.cuda()

y = model(x)
loss = nn.MSELoss()
l = loss(y, x)
optimizer.zero_grad()
l.backward()
optimizer.step()
print(l)
```

Any suggestion for resolving this? 
Thanks!

**Comment by ashantanu** [comment]
I have tried pointing colab to cuda 10.0 and 10.1 as well. Still not able to fix this.

**Comment by danielgehrig18** [comment]
Hi ashantanu, I will try to get it running on google colab and will let you know when how to do it once I succeed.

**Comment by danielgehrig18** [comment]
I think @iamsiddhantsahu will be able to help you.

**Comment by iamsiddhantsahu** [comment]
@ashantanu I too have encountered the same issues. I will be uploading the colab with the `esim_torch` installed, during the last week of October

**Comment by ashantanu** [comment]
@iamsiddhantsahu thanks! Can you point me to the issue? Maybe I can have a look at it meanwhile. Or are you going to upload a complied `esim_torch` to this repository?
