### ISSUE TITLE
Unable to install "esim_torch"

### ISSUE THREAD

**Issue by Srikarthikeyan4006** [uzh-rpg/rpg_vid2e#34]
```ERROR: Command errored out with exit status 1:
     command: /home/sk/anaconda3/envs/vid2e/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-1hhvtkhi/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-1hhvtkhi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-sycca_tk
         cwd: /tmp/pip-req-build-1hhvtkhi/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-1hhvtkhi/setup.py", line 9, in <module>
        'esim_cuda_kernel.cu',
      File "/home/sk/anaconda3/envs/vid2e/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 470, in CUDAExtension
        library_dirs += library_paths(cuda=True)
      File "/home/sk/anaconda3/envs/vid2e/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 548, in library_paths
        paths.append(_join_cuda_home(lib_dir))
      File "/home/sk/anaconda3/envs/vid2e/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1129, in _join_cuda_home
        raise EnvironmentError('CUDA_HOME environment variable is not set. '
    OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
    ----------------------------------------
WARNING: Discarding file:///home/sk/rpg_vid2e-master/esim_torch. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by hamdaan19** [comment]
@Srikarthikeyan4006 Can you please let us know what solved the issue?

**Comment by wyl-OvO** [comment]
Can you please let us know what solved the issue?
