### ISSUE TITLE
Installing ESIM Error

### ISSUE THREAD

**Issue by xiechuanyu** [uzh-rpg/rpg_vid2e#5]
Hi!

I am having an error by trying to build the python bindings for ESIM.
When I run pip install . in the esim_py folder, I got the following error:
```
  ERROR: Command errored out with exit status 1:
   command: /home/anaconda/envs/graph-wyx/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-6disk9bu/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-6disk9bu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-1ntzf6xt
       cwd: /tmp/pip-req-build-6disk9bu/
  Complete output (67 lines):
  running bdist_wheel
  running build
  running build_ext
  -- The C compiler identification is GNU 7.5.0
  -- The CXX compiler identification is GNU 7.5.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Error at CMakeLists.txt:4 (find_package):
    By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "pybind11",
    but CMake did not find one.
  
    Could not find a package configuration file provided by "pybind11" with any
    of the following names:
  
      pybind11Config.cmake
      pybind11-config.cmake
  
    Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
    "pybind11_DIR" to a directory containing one of the above files.  If
    "pybind11" provides a separate development package or SDK, be sure it has
    been installed.
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-req-build-6disk9bu/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-6disk9bu/setup.py", line 62, in <module>
      zip_safe=False,
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-6disk9bu/setup.py", line 31, in run
      self.build_extension(ext)
    File "/tmp/pip-req-build-6disk9bu/setup.py", line 49, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-6disk9bu', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-6disk9bu/build/lib.linux-x86_64-3.6', '-DPYTHON_EXECUTABLE=/home/anaconda/envs/graph-wyx/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for esim-py
  Running setup.py clean for esim-py
Failed to build esim-py
Installing collected packages: esim-py
    Running setup.py install for esim-py ... error
    ERROR: Command errored out with exit status 1:
     command: /home/anaconda/envs/graph-wyx/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-6disk9bu/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-6disk9bu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-hm8h6ckx/install-record.txt --single-version-externally-managed --compile --install-headers /home/anaconda/envs/graph-wyx/include/python3.6m/esim-py
         cwd: /tmp/pip-req-build-6disk9bu/
    Complete output (69 lines):
    running install
    running build
    running build_ext
    -- The C compiler identification is GNU 7.5.0
    -- The CXX compiler identification is GNU 7.5.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at CMakeLists.txt:4 (find_package):
      By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "pybind11",
      but CMake did not find one.
    
      Could not find a package configuration file provided by "pybind11" with any
      of the following names:
    
        pybind11Config.cmake
        pybind11-config.cmake
    
      Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
      "pybind11_DIR" to a directory containing one of the above files.  If
      "pybind11" provides a separate development package or SDK, be sure it has
      been installed.
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-req-build-6disk9bu/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-6disk9bu/setup.py", line 62, in <module>
        zip_safe=False,
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-6disk9bu/setup.py", line 31, in run
        self.build_extension(ext)
      File "/tmp/pip-req-build-6disk9bu/setup.py", line 49, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-6disk9bu', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-6disk9bu/build/lib.linux-x86_64-3.6', '-DPYTHON_EXECUTABLE=/home/anaconda/envs/graph-wyx/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/anaconda/envs/graph-wyx/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-6disk9bu/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-6disk9bu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-hm8h6ckx/install-record.txt --single-version-externally-managed --compile --install-headers /home/anaconda/envs/graph-wyx/include/python3.6m/esim-py Check the logs for full command output.
```

**Comment by xiechuanyu** [comment]
Another error. Why so many error ?
```
  ERROR: Command errored out with exit status 1:
   command: /home/anaconda/envs/graph-wyx/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-mfk1jouh/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-mfk1jouh/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-fviihesp
       cwd: /tmp/pip-req-build-mfk1jouh/
  Complete output (71 lines):
  running bdist_wheel
  running build
  running build_ext
  -- The C compiler identification is GNU 7.5.0
  -- The CXX compiler identification is GNU 7.5.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /home/anaconda/envs/graph-wyx/bin/python (found version "3.6.10")
  -- Found PythonLibs: /home/anaconda/envs/graph-wyx/lib/libpython3.6m.so
  -- Performing Test HAS_CPP14_FLAG
  -- Performing Test HAS_CPP14_FLAG - Success
  CMake Error at CMakeLists.txt:5 (find_package):
    By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "OpenCV", but
    CMake did not find one.
  
    Could not find a package configuration file provided by "OpenCV" with any
    of the following names:
  
      OpenCVConfig.cmake
      opencv-config.cmake
  
    Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
    "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
    provides a separate development package or SDK, be sure it has been
    installed.
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-req-build-mfk1jouh/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-mfk1jouh/setup.py", line 62, in <module>
      zip_safe=False,
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-mfk1jouh/setup.py", line 31, in run
      self.build_extension(ext)
    File "/tmp/pip-req-build-mfk1jouh/setup.py", line 49, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "/home/anaconda/envs/graph-wyx/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-mfk1jouh', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-mfk1jouh/build/lib.linux-x86_64-3.6', '-DPYTHON_EXECUTABLE=/home/anaconda/envs/graph-wyx/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for esim-py
  Running setup.py clean for esim-py
Failed to build esim-py
Installing collected packages: esim-py
    Running setup.py install for esim-py ... error
    ERROR: Command errored out with exit status 1:
     command: /home/anaconda/envs/graph-wyx/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-mfk1jouh/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-mfk1jouh/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-z9msddy6/install-record.txt --single-version-externally-managed --compile --install-headers /home/anaconda/envs/graph-wyx/include/python3.6m/esim-py
         cwd: /tmp/pip-req-build-mfk1jouh/
    Complete output (73 lines):
    running install
    running build
    running build_ext
    -- The C compiler identification is GNU 7.5.0
    -- The CXX compiler identification is GNU 7.5.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: /home/anaconda/envs/graph-wyx/bin/python (found version "3.6.10")
    -- Found PythonLibs: /home/anaconda/envs/graph-wyx/lib/libpython3.6m.so
    -- Performing Test HAS_CPP14_FLAG
    -- Performing Test HAS_CPP14_FLAG - Success
    CMake Error at CMakeLists.txt:5 (find_package):
      By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "OpenCV", but
      CMake did not find one.
    
      Could not find a package configuration file provided by "OpenCV" with any
      of the following names:
    
        OpenCVConfig.cmake
        opencv-config.cmake
    
      Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
      "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
      provides a separate development package or SDK, be sure it has been
      installed.
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-req-build-mfk1jouh/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-mfk1jouh/setup.py", line 62, in <module>
        zip_safe=False,
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-mfk1jouh/setup.py", line 31, in run
        self.build_extension(ext)
      File "/tmp/pip-req-build-mfk1jouh/setup.py", line 49, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/home/anaconda/envs/graph-wyx/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-mfk1jouh', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-mfk1jouh/build/lib.linux-x86_64-3.6', '-DPYTHON_EXECUTABLE=/home/anaconda/envs/graph-wyx/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/anaconda/envs/graph-wyx/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-mfk1jouh/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-mfk1jouh/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-z9msddy6/install-record.txt --single-version-externally-managed --compile --install-headers /home/anaconda/envs/graph-wyx/include/python3.6m/esim-py Check the logs for full command output.
```

**Comment by magehrig** [comment]
Did you follow all the steps (set up of the conda env) [here](https://github.com/uzh-rpg/rpg_vid2e#installation-with-anaconda)? Is your conda env active?

**Comment by xiechuanyu** [comment]
Thanks for your reply. Now it occurs error for `opencv`
- I have install all the package needed in my conda environment.
-  the output of`conda list | grep opencv` is shown below:
```
libopencv                 3.4.2                hb342d67_1  
opencv                    3.4.2            py36h6fd60c2_1  
py-opencv                 3.4.2            py36hb342d67_1
```
- There exists: `/home/anaconda/envs/graph-wyx/share/cmake/pybind11/pybind11Config.cmake`, but does not exist: `/home/anaconda/envs/graph-wyx/share/cmake/opencv/OpenCVConfig.cmake`.

**Comment by magehrig** [comment]
The file would most likely be: `/home/anaconda/envs/graph-wyx/share/OpenCV/OpenCVConfig.cmake`.

A workaround would be to manually check where OpenCVConfig.cmake is in your case and replace the line `find_package(OpenCV REQUIRED)` with
```
find_package(OpenCV REQUIRED PATHS YOURPATHTO/share/OpenCV NO_DEFAULT_PATH)
```
where `YOURPATHTO/share/OpenCV` is the directory that contains `OpenCVConfig.cmake`. I cannot help you, if you don't have this file.

**Comment by TxuanYu** [comment]
I have the same problem to find Opencv.

The error I got : 

```    running install
    running build
    running build_ext
    -- Building for: Visual Studio 16 2019
    -- The C compiler identification is MSVC 19.27.29112.0
    -- The CXX compiler identification is MSVC 19.27.29112.0
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: C:/Users/txuan/Anaconda3/envs/vid2e/python.exe (found version "3.7.9")
    -- Found PythonLibs: C:/Users/txuan/Anaconda3/envs/vid2e/libs/Python37.lib
    -- OpenCV ARCH: x64
    -- OpenCV RUNTIME:
    -- OpenCV STATIC: OFF
    CMake Warning at C:/Users/txuan/Anaconda3/envs/vid2e/Library/OpenCVConfig.cmake:156 (message):
      Found OpenCV Windows Pack but it has no binaries compatible with your
      configuration.

      You should manually point CMake variable OpenCV_DIR to your build of OpenCV
      library.
    Call Stack (most recent call first):
      CMakeLists.txt:5 (find_package)


    CMake Error at CMakeLists.txt:5 (find_package):
      Found package configuration file:

        C:/Users/txuan/Anaconda3/envs/vid2e/Library/OpenCVConfig.cmake

      but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
      NOT FOUND.
```

but if I change the code as @magehrig said
`find_package(OpenCV REQUIRED)`
to
`find_package(OpenCV REQUIRED PATHS C:/Users/txuan/Anaconda3/envs/vid2e/Library NO_DEFAULT_PATH)`

I got other error : 

```
    CMake Warning at C:/Users/txuan/Anaconda3/envs/vid2e/Library/OpenCVConfig.cmake:156 (message):
      Found OpenCV Windows Pack but it has no binaries compatible with your
      configuration.

      You should manually point CMake variable OpenCV_DIR to your build of OpenCV
      library.
    Call Stack (most recent call first):
      CMakeLists.txt:5 (find_package)


    CMake Error at CMakeLists.txt:5 (find_package):
      Found package configuration file:

        C:/Users/txuan/Anaconda3/envs/vid2e/Library/OpenCVConfig.cmake

      but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
      NOT FOUND.
```

Could you help me to solve this error?
