### ISSUE TITLE
Unsuccessful of command pip install rpg_vid2e/esim_py/

### ISSUE THREAD

**Issue by gwgknudayanga** [uzh-rpg/rpg_vid2e#61]
Hi,

When i tried to execute the command 'pip install rpg_vid2e/esim_py/'. It gave the following error.'
Is there any suggestion? (i am working in ubuntu)
rocessing ./rpg_vid2e/esim_py
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: esim-py
  Building wheel for esim-py (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [83 lines of output]
      running bdist_wheel
      running build
      running build_ext
      -- The C compiler identification is GNU 9.4.0
      -- The CXX compiler identification is GNU 9.4.0
      -- Check for working C compiler: /usr/bin/cc
      -- Check for working C compiler: /usr/bin/cc -- works
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Check for working CXX compiler: /usr/bin/c++
      -- Check for working CXX compiler: /usr/bin/c++ -- works
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found PythonInterp: /home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/bin/python (found version "3.9.12")
      -- Found PythonLibs: /home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/libpython3.9.so
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Found pybind11: /home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/include (found version "2.6.1" )
      CMake Error at CMakeLists.txt:5 (find_package):
        By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "OpenCV", but
        CMake did not find one.
      
        Could not find a package configuration file provided by "OpenCV" with any
        of the following names:
      
          OpenCVConfig.cmake
          opencv-config.cmake
      
        Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
        "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
        provides a separate development package or SDK, be sure it has been
        installed.
      
      
      -- Configuring incomplete, errors occurred!
      See also "/home/dtu-neurorobotics-desk2/Research_Work/Video2Events_ESIM/rpg_vid2e/esim_py/build/temp.linux-x86_64-cpython-39/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/dtu-neurorobotics-desk2/Research_Work/Video2Events_ESIM/rpg_vid2e/esim_py/setup.py", line 53, in <module>
          setup(
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/command/build.py", line 24, in run
          super().run()
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/dtu-neurorobotics-desk2/Research_Work/Video2Events_ESIM/rpg_vid2e/esim_py/setup.py", line 31, in run
          self.build_extension(ext)
        File "/home/dtu-neurorobotics-desk2/Research_Work/Video2Events_ESIM/rpg_vid2e/esim_py/setup.py", line 49, in build_extension
          subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/home/dtu-neurorobotics-desk2/Research_Work/Video2Events_ESIM/rpg_vid2e/esim_py', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/dtu-neurorobotics-desk2/Research_Work/Video2Events_ESIM/rpg_vid2e/esim_py/build/lib.linux-x86_64-cpython-39', '-DPYTHON_EXECUTABLE=/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for esim-py
  Running setup.py clean for esim-py
Failed to build esim-py
Installing collected packages: esim-py
  Running setup.py install for esim-py ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for esim-py did not run successfully.
  │ exit code: 1
  ╰─> [87 lines of output]
      running install
      /home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      -- The C compiler identification is GNU 9.4.0
      -- The CXX compiler identification is GNU 9.4.0
      -- Check for working C compiler: /usr/bin/cc
      -- Check for working C compiler: /usr/bin/cc -- works
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Check for working CXX compiler: /usr/bin/c++
      -- Check for working CXX compiler: /usr/bin/c++ -- works
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found PythonInterp: /home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/bin/python (found version "3.9.12")
      -- Found PythonLibs: /home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/libpython3.9.so
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Found pybind11: /home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/include (found version "2.6.1" )
      CMake Error at CMakeLists.txt:5 (find_package):
        By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "OpenCV", but
        CMake did not find one.
      
        Could not find a package configuration file provided by "OpenCV" with any
        of the following names:
      
          OpenCVConfig.cmake
          opencv-config.cmake
      
        Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
        "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
        provides a separate development package or SDK, be sure it has been
        installed.
      
      
      -- Configuring incomplete, errors occurred!
      See also "/home/dtu-neurorobotics-desk2/Research_Work/Video2Events_ESIM/rpg_vid2e/esim_py/build/temp.linux-x86_64-cpython-39/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/dtu-neurorobotics-desk2/Research_Work/Video2Events_ESIM/rpg_vid2e/esim_py/setup.py", line 53, in <module>
          setup(
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 692, in run
          self.run_command('build')
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/command/build.py", line 24, in run
          super().run()
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/dtu-neurorobotics-desk2/Research_Work/Video2Events_ESIM/rpg_vid2e/esim_py/setup.py", line 31, in run
          self.build_extension(ext)
        File "/home/dtu-neurorobotics-desk2/Research_Work/Video2Events_ESIM/rpg_vid2e/esim_py/setup.py", line 49, in build_extension
          subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
        File "/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/home/dtu-neurorobotics-desk2/Research_Work/Video2Events_ESIM/rpg_vid2e/esim_py', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/dtu-neurorobotics-desk2/Research_Work/Video2Events_ESIM/rpg_vid2e/esim_py/build/lib.linux-x86_64-cpython-39', '-DPYTHON_EXECUTABLE=/home/dtu-neurorobotics-desk2/anaconda3/envs/vid2e/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> esim-py

**Comment by gwgknudayanga** [comment]
this is working now . Thanks .

**Comment by RahulECE** [comment]
how did you solved the problem?
