### ISSUE TITLE
python upsample.py error, missing pretrained model

### ISSUE THREAD

**Issue by senecobis** [uzh-rpg/rpg_vid2e#76]
Hi thank you for the release.
If I’m not mistaken no one mentioned this issue but I’ve seen that after running out-of-the-box the command for sampling 
`python upsampling/upsample.py --input_dir=example/original --output_dir=example/upsampled` 
it seems to be missing some pretrained models, that I don’t really see where they should be taken. 

The following is the output:

`Traceback (most recent call last):
  File "/home/pellerito/rpg_vid2e/upsampling/upsample.py", line 27, in <module>
    main()
  File "/home/pellerito/rpg_vid2e/upsampling/upsample.py", line 22, in main
    upsampler = Upsampler(input_dir=flags.input_dir, output_dir=flags.output_dir)
  File "/home/pellerito/rpg_vid2e/upsampling/utils/upsampler.py", line 26, in __init__
    self.interpolator = Interpolator(path, None)
  File "/home/pellerito/rpg_vid2e/upsampling/utils/interpolator.py", line 82, in __init__
    self._model = tf.compat.v2.saved_model.load(model_path)
  File "/home/pellerito/anaconda3/envs/vid2e/lib/python3.9/site-packages/tensorflow/python/saved_model/load.py", line 864, in load
    result = load_internal(export_dir, tags, options)["root"]
  File "/home/pellerito/anaconda3/envs/vid2e/lib/python3.9/site-packages/tensorflow/python/saved_model/load.py", line 878, in load_internal
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "/home/pellerito/anaconda3/envs/vid2e/lib/python3.9/site-packages/tensorflow/python/saved_model/loader_impl.py", line 60, in parse_saved_model_with_debug_info
    saved_model = _parse_saved_model(export_dir)
  File "/home/pellerito/anaconda3/envs/vid2e/lib/python3.9/site-packages/tensorflow/python/saved_model/loader_impl.py", line 118, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: /home/pellerito/rpg_vid2e/upsampling/utils/../../pretrained_models/film_net/Style/saved_model/{saved_model.pbtxt|saved_model.pb}`

**Comment by senecobis** [comment]
Downloading pertained models here https://github.com/google-research/frame-interpolation#pre-trained-models solves the issue
