### ISSUE TITLE
error building for esim_py

### ISSUE THREAD

**Issue by yazidoudou18** [uzh-rpg/rpg_vid2e#77]
Processing ./esim_py
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: esim-py
  Building wheel for esim-py (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      running bdist_wheel
      running build
      running build_ext
      -- The CXX compiler identification is unknown
      CMake Error at CMakeLists.txt:2 (project):
        No CMAKE_CXX_COMPILER could be found.
      
        Tell CMake where to find the compiler by setting either the environment
        variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
        to the compiler, or to the compiler name if it is in the PATH.
      
      
      -- Configuring incomplete, errors occurred!
      See also "/qfs/projects/mage/watk681/rpg_vid2e/esim_py/build/temp.linux-x86_64-cpython-39/CMakeFiles/CMakeOutput.log".
      See also "/qfs/projects/mage/watk681/rpg_vid2e/esim_py/build/temp.linux-x86_64-cpython-39/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/qfs/projects/mage/watk681/rpg_vid2e/esim_py/setup.py", line 53, in <module>
          setup(
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/qfs/projects/mage/watk681/rpg_vid2e/esim_py/setup.py", line 31, in run
          self.build_extension(ext)
        File "/qfs/projects/mage/watk681/rpg_vid2e/esim_py/setup.py", line 49, in build_extension
          subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/qfs/projects/mage/watk681/rpg_vid2e/esim_py', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/qfs/projects/mage/watk681/rpg_vid2e/esim_py/build/lib.linux-x86_64-cpython-39', '-DPYTHON_EXECUTABLE=/home/watk681/anaconda3/envs/vid2e/bin/python3.9', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for esim-py
  Running setup.py clean for esim-py
Failed to build esim-py
Installing collected packages: esim-py
  Running setup.py install for esim-py ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for esim-py did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      running install
      /home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      -- The C compiler identification is GNU 9.4.0
      -- The CXX compiler identification is unknown
      -- Check for working C compiler: /usr/bin/cc
      -- Check for working C compiler: /usr/bin/cc -- works
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Detecting C compile features
      -- Detecting C compile features - done
      CMake Error at CMakeLists.txt:2 (project):
        No CMAKE_CXX_COMPILER could be found.
      
        Tell CMake where to find the compiler by setting either the environment
        variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
        to the compiler, or to the compiler name if it is in the PATH.
      
      
      -- Configuring incomplete, errors occurred!
      See also "/qfs/projects/mage/watk681/rpg_vid2e/esim_py/build/temp.linux-x86_64-cpython-39/CMakeFiles/CMakeOutput.log".
      See also "/qfs/projects/mage/watk681/rpg_vid2e/esim_py/build/temp.linux-x86_64-cpython-39/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/qfs/projects/mage/watk681/rpg_vid2e/esim_py/setup.py", line 53, in <module>
          setup(
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 697, in run
          self.run_command('build')
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/qfs/projects/mage/watk681/rpg_vid2e/esim_py/setup.py", line 31, in run
          self.build_extension(ext)
        File "/qfs/projects/mage/watk681/rpg_vid2e/esim_py/setup.py", line 49, in build_extension
          subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
        File "/home/watk681/anaconda3/envs/vid2e/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/qfs/projects/mage/watk681/rpg_vid2e/esim_py', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/qfs/projects/mage/watk681/rpg_vid2e/esim_py/build/lib.linux-x86_64-cpython-39', '-DPYTHON_EXECUTABLE=/home/watk681/anaconda3/envs/vid2e/bin/python3.9', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> esim-py

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by saratrajput** [comment]
@yazidoudou18  I have the same issue as well. Were you able to find a solution?
