### ISSUE TITLE
Failed building wheel for esim-torch

### ISSUE THREAD

**Issue by emanehabn** [uzh-rpg/rpg_vid2e#80]
Hello,

I hope you are fine and safe.

I'm trying to install esim-torch but I got this error, 
Note: cuda version outside the env is 11.2

> (vid2e) eman@eman:~/Documents/AUC/ESIM$ pip install rpg_vid2e/esim_torch/
Processing ./rpg_vid2e/esim_torch
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: esim-torch
  Building wheel for esim-torch (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/esim_torch
      copying src/esim_torch/esim_torch.py -> build/lib.linux-x86_64-cpython-39/esim_torch
      copying src/esim_torch/__init__.py -> build/lib.linux-x86_64-cpython-39/esim_torch
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/eman/Documents/AUC/ESIM/rpg_vid2e/esim_torch/setup.py", line 4, in <module>
          setup(
        File "/home/eman/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/eman/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/eman/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/eman/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/eman/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/eman/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/eman/anaconda3/envs/vid2e/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/home/eman/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/eman/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/eman/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/eman/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/eman/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/eman/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/eman/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/eman/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/eman/anaconda3/envs/vid2e/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/eman/anaconda3/envs/vid2e/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "/home/eman/anaconda3/envs/vid2e/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 383, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "/home/eman/anaconda3/envs/vid2e/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 52, in parse
          return Version(version)
        File "/home/eman/anaconda3/envs/vid2e/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 196, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for esim-torch
  Running setup.py clean for esim-torch
Failed to build esim-torch
ERROR: Could not build wheels for esim-torch, which is required to install pyproject.toml-based projects

**Comment by emanehabn** [comment]
Hello there,

I found that the reason of the error is that the downloaded torch libraries are not compatible with cudatoolkit 11.3. So install these libraries:

`pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113`

Also, check that you use the required version of nvidia-driver: 460, cuda: 10.2, cudnn: v8.1.0.77

This [article](https://medium.com/analytics-vidhya/install-cuda-11-2-cudnn-8-1-0-and-python-3-9-on-rtx3090-for-deep-learning-fcf96c95f7a1) helped me specifically for cudnn installation (better download the linux tgs file and compile it as mentioned in the article not the .deb package)

Hope this help!!!
