### ISSUE TITLE
ERROR: Could not build wheels for esim-py, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by Weihua-Wang** [uzh-rpg/rpg_vid2e#85]
When I build the python bindings for ESIM using 
/pip install rpg_vid2e/esim_py/ I met the following errors. 
```cmake
Processing c:\users\asus\pycharmprojects\visevent\vid2e\rpg_vid2e\esim_py
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: esim-py
  Building wheel for esim-py (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [102 lines of output]
      running bdist_wheel
      running build
      running build_ext
      C:\Users\ASUS\PycharmProjects\VisEvent\vid2e\rpg_vid2e\esim_py\setup.py:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        cmake_version = LooseVersion(re.search(r'version\s*([\d.]+)', out.decode()).group(1))
      -- Building for: Visual Studio 17 2022
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      -- Selecting Windows SDK version 10.0.20348.0 to target Windows 10.0.19044.
      -- The C compiler identification is MSVC 19.38.33130.0
      -- The CXX compiler identification is MSVC 19.38.33130.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Warning (dev) at C:/Users/ASUS/anaconda3/envs/vid2e/Library/share/cmake/pybind11/FindPythonLibsNew.cmake:98 (find_package):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.

      Call Stack (most recent call first):
        C:/Users/ASUS/anaconda3/envs/vid2e/Library/share/cmake/pybind11/pybind11Tools.cmake:50 (find_package)
        C:/Users/ASUS/anaconda3/envs/vid2e/Library/share/cmake/pybind11/pybind11Common.cmake:188 (include)
        C:/Users/ASUS/anaconda3/envs/vid2e/Library/share/cmake/pybind11/pybind11Config.cmake:250 (include)
        CMakeLists.txt:4 (find_package)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Found PythonInterp: C:/Users/ASUS/anaconda3/envs/vid2e/python.exe (found suitable version "3.9.18", minimum required is "3.6")
      -- Found PythonLibs: C:/Users/ASUS/anaconda3/envs/vid2e/libs/python39.lib
      -- Performing Test HAS_MSVC_GL_LTCG
      -- Performing Test HAS_MSVC_GL_LTCG - Success
      -- Found pybind11: C:/Users/ASUS/anaconda3/envs/vid2e/Library/include (found version "2.11.1")
      CMake Error at CMakeLists.txt:5 (find_package):
        By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "OpenCV", but
        CMake did not find one.

        Could not find a package configuration file provided by "OpenCV" with any
        of the following names:

          OpenCVConfig.cmake
          opencv-config.cmake

        Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
        "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
        provides a separate development package or SDK, be sure it has been
        installed.


      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ASUS\PycharmProjects\VisEvent\vid2e\rpg_vid2e\esim_py\setup.py", line 53, in <module>
          setup(
        File "C:\Users\ASUS\AppData\Roaming\Python\Python39\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\ASUS\AppData\Roaming\Python\Python39\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\ASUS\AppData\Roaming\Python\Python39\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\ASUS\AppData\Roaming\Python\Python39\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\ASUS\AppData\Roaming\Python\Python39\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\ASUS\AppData\Roaming\Python\Python39\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\ASUS\AppData\Roaming\Python\Python39\site-packages\wheel\bdist_wheel.py", line 369, in run
          self.run_command("build")
        File "C:\Users\ASUS\AppData\Roaming\Python\Python39\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\ASUS\AppData\Roaming\Python\Python39\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\ASUS\AppData\Roaming\Python\Python39\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\ASUS\AppData\Roaming\Python\Python39\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\ASUS\AppData\Roaming\Python\Python39\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\ASUS\AppData\Roaming\Python\Python39\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\ASUS\AppData\Roaming\Python\Python39\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\ASUS\PycharmProjects\VisEvent\vid2e\rpg_vid2e\esim_py\setup.py", line 31, in run
          self.build_extension(ext)
        File "C:\Users\ASUS\PycharmProjects\VisEvent\vid2e\rpg_vid2e\esim_py\setup.py", line 49, in build_extension
          subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
        File "C:\Users\ASUS\anaconda3\envs\vid2e\lib\subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\ASUS\\PycharmProjects\\VisEvent\\vid2e\\rpg_vid2e\\esim_py', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\ASUS\\PycharmProjects\\VisEvent\\vid2e\\rpg_vid2e\\esim_py\\build\\lib.win-amd64-cpython-39', '-DPYTHON_EXECUTABLE=C:\\Users\\ASUS\\anaconda3\\envs\\vid2e\\python.exe', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for esim-py
  Running setup.py clean for esim-py
Failed to build esim-py
ERROR: Could not build wheels for esim-py, which is required to install pyproject.toml-based projects
```

**Comment by ofer-baroz** [comment]
Any news on this topic?
Having troubles instaling esim_py as well
